---
title: "Publications"
editor: visual
---

::: callout-note
## Links

> -   **Google Scholar**: <https://scholar.google.com/citations?user=PHMJIw4AAAAJ&hl=en>
> -   **ORCID**: <https://orcid.org/0000-0003-2508-9163>
> -   **ResearchGate:** <https://www.researchgate.net/profile/Di-Zhao-21?ev=prf_overview>
:::

 

## 期刊论文

1.  Chao Chen, **Di Zhao\***, and Sei Zhen Khong, “The singular angle of nonlinear systems,” *Automatica* (**Regular paper**), 2025, To appear.
2.  Lanlan Su, **Di Zhao\***, and Sei Zhen Khong, “On the exponential convergence of input-output signals of nonlinear feedback systems,” *IEEE Transactions on Automatic Control*, 2025, online.
3.  Weihao Zhang, **Di Zhao\***, and Shu Liang, “Soft safety analysis of interconnected systems,” *IEEE Transactions on Automatic Control* (**Regular paper**), 2025, 70(7): 4315-4329.
4.  Jianqi Chen, Qi Mao\*, **Di Zhao**, Chao Chen, “Robust stability and stabilizability conditions for time-delay systems under stochastic uncertainties,” *IEEE Transactions on Automatic Control*, 2025, 70(6): 4037-4044.
5.  Jiajin Liang, **Di Zhao**\*, Li Qiu, “Feedback stability under mixed gain and phase uncertainty,” *IEEE Transactions on Automatic Control* (**Regular paper**), 2024, 1-16.
6.  Sei Zhen Khong**, Di Zhao**\*, Alexander Lanzon, “Converse negative imaginary theorems,” *Automatica*, 2024, 165: 111682.
7.  **Di Zhao**, Chao Chen\*, Jianqi Chen, “Small gain and small angle conditions for feedback stability analysis of linear stochastic systems,” *IEEE Transactions on Automatic Control*, 2023, 69(5): 3349-3356.
8.  Tianqiu Yu\*, **Di Zhao**, Li Qiu, “Phases of sectorial operators,” *Integral Equations and Operator Theory*, 2023, vol. 95, no. 31.
9.  **Di Zhao**\*, Sei Zhen Khong, Li Qiu, “System monotonicity and subspace tracking: A geometric perspective of the Frisch–Shapiro scheme,” *IEEE Transactions on Automatic Control* (**Regular paper**), 2022, 67(11): 5872-5884.
10. **Di Zhao**, Chao Chen\*, Sei Zhen Khong, “A frequency-domain approach to nonlinear negative imaginary systems analysis,” *Automatica*, 2022, 146: 110604.
11. **Di Zhao**\*, Axel Ringh, Li Qiu, Sei Zhen Khong, “Low phase-rank approximation,” *Linear Algebra and its Applications*, 2022, 639: 177-204.
12. **Di Zhao**, Li Qiu\*, “Retrospect and prospect on integration of gain and phase for feedback stability analysis,” *Control Theory and Technology*, 2022, 20(4): 555-558.
13. **Di Zhao**, Yi Dong\*, “Recent advances on micro-control for near-critical complex systems,” *Control Theory and Technology*, 2022, 20(2): 287-290.
14. **Di Zhao**\*, Sei Zhen Khong, Li Qiu, “Stabilization of cascaded two-port networked systems with simultaneous nonlinear uncertainties,” *Automatica*, 2021, 123: 109360.
15. Tianqiu Yu\*, **Di Zhao**, Li Qiu, “Networked robust stability for LTV systems with simultaneous uncertainties in plant, controller, and communication channels,” *SIAM Journal on Control and Optimization*, 2021, 59(1): 1-23.
16. **Di Zhao**\*, Li Qiu, Guoxiang Gu, “Stabilization of two-port networked systems with simultaneous uncertainties in plant, controller, and communication channels,” *IEEE Transactions on Automatic Control* (**Regular paper**), 2020, 65(3): 1160-1175.

## 会议论文

1.  Jiajin Liang, **Di Zhao**, Li Qiu, “Sectored-disk problems and robust stability under mixed gain and phase uncertainty,” 26th International Symposium on Mathematical Theory of Networks and Systems (MTNS), Cambridge, UK, 2024.

2.  Chao Chen, Wei Chen, **Di Zhao**, Jianqi Chen, Li Qiu, “A cyclic small phase theorem for MIMO LTI systems,” 22nd IFAC World Congress, Yokohama, Japan, 2023.

3.  **Di Zhao**, “Low phase-rank approximation and its application for asymmetry reduction of digraphs,” 42nd Chinese Control Conference (CCC), Tianjin, China, 2023.

4.  **Di Zhao**, Wei Chen, Li Qiu, “When small gain meets small phase,” 41st Chinese Control Conference (CCC), online, China, 2022.

5.  Chao Chen, **Di Zhao**, W. Chen, Li Qiu, “A nonlinear small-phase theorem,” 21st IFAC World Congress, Berlin, Germany, 2020.

6.  **Di Zhao**, Sei Zhen Khong, Li Qiu “Stabilization of two-port NCSs with simultaneous uncertainties,” 40th Chinese Control Conference (CCC), Shanghai, China, 2021.

7.  **Di Zhao**, Sei Zhen Khong, Li Qiu, “Stabilization of cascaded two-port networked systems against nonlinear perturbations,” IEEE 56th Annual Conference on Decision and Control (CDC), Melbourne, Australia, 2017, pp. 1042-1045, 2017.

8.  **Di. Zhao**, Li Qiu, “Stability of networked feedback system with frequency-wise bounded uncertainty quartets,” *11th Asian Control Conference (ASCC)*, Gold Coast, Australia, 2017, pp. 1980-1983, 2017.

9.  **Di Zhao**, Li Qiu, “Networked robust stabilization with simultaneous uncertainties in plant, controller and communication channels,” IEEE 55th Conference on Decision and Control (CDC), Las Vegas, NV, 2016, pp. 2376-2381, 2016.

10. **Di Zhao**, Anders Rantzer, Li Qiu, “A convex approach to Frisch-Kalman problem,” IEEE 58th Annual Conference on Decision and Control (CDC), Nice, France, pp. 7154-7158, 2019.

11. Chao Chen, **Di Zhao**, Li Qiu, “Control of an under-sensed and under-actuated linear inverted pendulum,” The SICE Annual Conference (SICE), Nara, Japan, 2018.

## 章节论文

1.  **Di Zhao**, Chao Chen, Sei Zhen Khong, Li Qiu\*, “Robust control against uncertainty quartet: A polynomial approach,” In T. Basar (eds), Uncertainty in Complex Networked Systems. Systems & Control: Foundations & Applications. Birkhauser, Cham, pp. 149-178, 2018.

2.  Li Qiu\*, **Di Zhao**, “Robust control in gap metric,” In: J. Baillieul and T. Samad (eds), Encyclopedia of Systems and Control, Springer, London, 2019.

## 筹备/审稿中的论文

1.  Chao Chen, Wei Chen, **Di Zhao**, Jianqi Chen, Li Qiu\*, “A cyclic small phase theorem,” *IEEE Transactions on Automatic Control*, under review.

2.  Sei Zhen Khong**, Di Zhao**\*, Alexander Lanzon, “Extended strictly negative imaginary systems and associated robust feedback stability,” *Automatica*, under review.

3.  Haoxiang Yang, **Di Zhao**\*, Jun Shang, “Safety verification for linear time-varying systems under ellipsoidal constraints,” *IEEE Transactions on Automatic Control*, under review.

4.  Weihao Zhang, Chao Chen, Jianqi Chen, **Di Zhao**\*, “Angular safety analysis of interconnected systems,” in preparation.

5.  **Di Zhao**, Chao Chen, Jianqi Chen\*, “Feedback stability of linear time-varying stochastic systems:  A passivity approach,” in preparation.

## 科研项目

1.  国家自然科学基金，面上项目，相位不确定性下复杂系统的鲁棒安全控制理论与方法，2026-01-01 至2029-12-31，50万元，主持。

2.  国家自然科学基金，青年科学基金，基于相位秩优化的无人自主系统模型降阶方法研究，2022-01-01 至2024-12-31，30万元，主持。

3.  国家重点研发计划子课题，高动态约束下快速最优决策，2022-12-01至2027-11-30，70万元，主持。

4.  教育部中国高校产学研创新基金，火场等极端环境下的多自主体安全协同理论与方法，2023-09-01 至 2024-08-31 2万元，主持。

5.  同济大学自主原创基础研究项目，基于相位控制的网络鲁棒安全性理论，2024-04-01至2026-03-31，12万元 ，主持。

6.  国家自然科学基金面上项目，智能无人集群系统在线反馈的安全决策控制一体化设计与分析，2024-01-01 至2027-12-31，50万元，参与。

7.  国家自然科学基金面上项目，基于联邦学习机制的半导体智能制造系统异构分布式调度优化，2022-01-01 至2025-12-31，57万元 ，参与。

8.  深港澳科技计划 （C类），复杂系统相位理论应用于多动子物料传输系统的协同控制，2021-07-30 至 2023-07-30，100万元，参与。